In [3]:
import cv2
import numpy as np

In [4]:
image = cv2.imread('DATA/input.jpg')

### HSV Channel

In [5]:
image.shape

(830, 1245, 3)

(830, 1245, 3)

In [ ]:
cv2.COLOR_BGR2LAB

In [10]:
hsv_image = cv2.cvtColor(image, cv2.cv2.COLOR_BGR2LAB)

In [11]:
hsv_image[:, :, 0]  #[start_row:stop_Row,   start_col:stop_col,    chanel ]

array([[17, 17, 16, ..., 26, 26, 26],
       [17, 17, 17, ..., 26, 26, 26],
       [17, 17, 17, ..., 26, 26, 26],
       ...,
       [ 6,  6,  6, ..., 25, 26, 27],
       [ 5,  5,  5, ..., 25, 26, 27],
       [ 5,  5,  3, ..., 25, 25, 26]], dtype=uint8)

array([[17, 17, 16, ..., 26, 26, 26],
       [17, 17, 17, ..., 26, 26, 26],
       [17, 17, 17, ..., 26, 26, 26],
       ...,
       [ 6,  6,  6, ..., 25, 26, 27],
       [ 5,  5,  5, ..., 25, 26, 27],
       [ 5,  5,  3, ..., 25, 25, 26]], dtype=uint8)

In [12]:
hsv_image.shape

(830, 1245, 3)

(830, 1245, 3)

In [13]:
cv2.imshow('HSV image', hsv_image)
cv2.imshow('Hue channel', hsv_image[:, :, 0])
cv2.imshow('Saturation channel', hsv_image[:, :, 1])
cv2.imshow('Value channel', hsv_image[:, :, 2])

cv2.waitKey()
cv2.destroyAllWindows()

### RGB Channel

In [14]:
image = cv2.imread('DATA/cat.jpeg')

In [ ]:
image.shape

In [15]:
# OpenCV's 'split' function splites the image into each color index
B, G, R = cv2.split(image)

print(B.shape)

(350, 528)
(350, 528)


In [18]:
cv2.imshow("org", image)
cv2.imshow("Red", R)
cv2.imshow("Green", G)
cv2.imshow("Blue", B)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.destroyAllWindows()

In [24]:
# # # Let's re-make the original image, 
# merged = cv2.merge([R, G, B]) 
# cv2.imshow("Merged", merged) 


# Let's amplify the blue color
merged = cv2.merge([B+40, G+12, R+152])
cv2.imshow("Merged with Blue Amplified", merged) 

cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
image.shape[:2]

(350, 528)

(350, 528)

In [27]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
z = np.zeros(shape=(image.shape[:2]), dtype="uint8")

In [30]:
b, g, r = cv2.split(image)

In [31]:

cv2.imshow("blue", cv2.merge([b, z, z]))
cv2.imshow("Green", cv2.merge([z,g, z]))
cv2.imshow("red",cv2.merge([z, z, r]))
cv2.waitKey(0)
cv2.destroyAllWindows()